In [1]:
from glob import glob
import pandas as pd

In [2]:
file_paths = sorted(glob("./data/preproc_data/*.csv"))

In [3]:
read_csv = lambda file_path: pd.read_csv(file_path, index_col=0)

In [4]:
crime_df = pd.concat([read_csv(file_path) for file_path in file_paths], axis=0)

In [5]:
display(crime_df.sample(5))
display(crime_df[(crime_df["지역"] == "서울") & (crime_df["범죄중분류"] == "마약범죄")])

     범죄대분류 범죄중분류     지역 Count      date
2119  마약범죄  마약범죄  전북 김제     3  20201231
1612  폭력범죄    손괴  강원 태백    49  20211231
2394  강력범죄  살인기수  전남 순천     2  20221231
2553  강력범죄    방화  경북 구미     9  20161231
2545  기타범죄  기타범죄  경북 경주   870  20171231

   범죄대분류 범죄중분류  지역   Count      date
26  마약범죄  마약범죄  서울     698  20121231
29  마약범죄  마약범죄  서울     877  20131231
29  마약범죄  마약범죄  서울    1098  20141231
29  마약범죄  마약범죄  서울    1360  20151231
29  마약범죄  마약범죄  서울    1449  20161231
29  마약범죄  마약범죄  서울    1746  20171231
29  마약범죄  마약범죄  서울  1544.0  20181231
29  마약범죄  마약범죄  서울    1884  20191231
29  마약범죄  마약범죄  서울    2154  20201231
29  마약범죄  마약범죄  서울    2275  20211231
29  마약범죄  마약범죄  서울    2821  20221231

In [6]:
crime_df['지역'].value_counts()

지역
서울        419
강원 춘천     419
경기 평택     419
경북 경주     419
경남 김해     419
         ...
경기 하남     308
경기 화성     308
강원 동해     308
제주 서귀포    308
경남 마산     111
Name: count, Length: 88, dtype: int64